### ISSUE TITLE
gohan validate cannot validate schema with multiple files

### ISSUE THREAD

**Issue by morrisson** [cloudwan/gohan#178]
gohan validate -d <schema_file> can only one schema file. Therefore, if schema files are separated into A and B, and some resource in a file B depends on other in a file A, validation of a file B fails.

One of the problem is current 'd' flag of gohan validate is StringFlag, therefore only one value is accepted. I propose this should be changed to StringSliceFlag to accept multiple values for -d.

**Comment by nati** [comment]
+1
