### ISSUE TITLE
idea / question: UI integration

### ISSUE THREAD

**Issue by joeblew99** [cloudwan/gohan#241]
i have not used gohan yet, so go easy :)

As i understand it gohan acts like a wrapper for your microservices, putting policy aspects there too. I am sure it does lots more too.

So, i want to use this with a react based from end, or maybe just any front end.
There is a ton of boilerplate that i think can be code generated that the JS / Gopgerjs Client could use.
This would make it much easier to keep the UI and the Gohan layer in sync in terms of compiling together i feel.

Has anyone else though about this ? Any plans, examples.

**Comment by nati** [comment]
Hi Joe

Thank for your interest in this project.
We have two options for your questions.

(1) Interpret schema on the fly

We have webui project for gohan.
https://github.com/cloudwan/gohan_webui

This is pure js app, and it interprets gohan schema. so we can have CRUD view without generating any 
code. We are going to apply react for this UI too.

(2) gohan template command
There is CLI option called "template".
You can apply pongo2 template (it is jinja2 like template implemented in go ) for the template.
We implemented to command to generate markdown (gohan markdown) or dot file (gohan dot) using this command, and you can write also your template to generate your client.

**Comment by joeblew99** [comment]
Sounds great.

Really like the way the project is designed.

I dont know if you know about these, but there are some great generators for react that might help allot.
This project is using a meta data tre to describe all the relationships and then has 2 "pre-packs" to generate from.

https://helmetrex.com/projects
It has its own web GUi for accessing the pre-packs also.


Would be curious what you think.

**Comment by nati** [comment]
For custom UX page, you can use custom app routes in gohan webui.

https://github.com/cloudwan/gohan_webui/blob/master/app/config.json.sample#L7

GraphQL or relact prepack looks interesting. but we don't have urgent usecase for them right now.
Contributions are welcome :)

**Comment by joeblew99** [comment]
thanks.

I wlll try to work it out. Its a bit opaque at the moment, but i know your
still working things out and finishing things off.

**Comment by nati** [comment]
Thanks. anything you feel it is opaque, it is our doc bug. so it is great if we can have a change to improve it

**Comment by joeblew99** [comment]
It's understandable. It's looking awesome and with some more samples doc it
will be great.

**Comment by joeblew99** [comment]
Shall I close this ?

**Comment by nati** [comment]
got it. Thanks .
let me close this issue
