### ISSUE TITLE
gohan_http doesn't allow to not follow redirects

### ISSUE THREAD

**Issue by altran01** [cloudwan/gohan#253]
In current version gohan_http uses default go http.Client behavior which is to automatically follow up to 10 redirects and return last response. Unfortunately it's not always the desired behaviour. In our current use-case we want to use gohan_http to login to web service which responds to POST login request with 302 redirect containing new sessionid in "Set-Cookie" header, however http.Client then follows this redirect using old headers (and old sessionid - from before login) to which server responds with login page again - and this new response doesn't contain new authorized sessionid.

The solution to this is to use http.Transport and its method RoundTrip directly, which doesn't handle redirects.

@nati - which approach would prefer - adding something like followRedirects argument to gohan_http which would decide whether we use http.Client or http.RoundTrip, or create new builtin - gohan_http_raw, which wouldn't be hindered by default http.Client behaviors and allow developer to have full control over requests, if he decides that he needs it?

**Comment by nati** [comment]
i'm ok with adding new api.  
Closing this because the patch merged
