### ISSUE TITLE
gohan_http doesn't allow to send requests with content-type different than "text/plain" and "application/json"

### ISSUE THREAD

**Issue by altran01** [cloudwan/gohan#254]
Currently gohan_http checks if content-type is present and equal to "text/plain" in provided headers, if so it uses provided data without changes. In other situation it assumes that we want to use "application/json", it will overwrite current content-type and use json.Marshal on data.

This causes that one is unable to for example send request with "application/x-www-form-urlencoded".

I think that the better behavior would be to only use "application/json" only if no content-type was provided, and assume that extension formated data according to its requested content-type.

**Comment by nati** [comment]
code merged
