### ISSUE TITLE
Versioned Config

### ISSUE THREAD

**Issue by morrisson** [cloudwan/gohan#263]
Currently, we can set state_versioning for some resources. This feature is mainly used to receive backend states asynchronously.

However, an user can create some resource then immediately update some data before the backend response of create request. In this time, the config version becomes 2 so gohan cannot get version-1 config. Due to this, gohan might not be able to get data to do something on state update of resource creation (config 1).

Gohan should keep version history of configs until at least state update for the config version is coming from backend.

**Comment by nati** [comment]
Gohan shouldn't keep history.
In that case, worker should update state based on config 2.
