### ISSUE TITLE
Runtime metrics

### ISSUE THREAD

**Issue by p-kozlowski** [cloudwan/gohan#449]
I'd like to expose runtime metrics, like number of requests processed per second or min/max/avg request processing time. I was thinking of using https://github.com/rcrowley/go-metrics. This way Gohan could be easily integrated with monitoring frameworks like Graphite/Prometheus/ELK.

@nati, @astralblue, @marcin-ptaszynski, @przemyslaw-dobrowolski-cl what do you think about it?

**Comment by marcin-ptaszynski** [comment]
Looks abstracted enough, that it can be used in generic layer and be fully configurable.

**Comment by p-kozlowski** [comment]
Done in #464
