### ISSUE TITLE
Parent relationship order matters

### ISSUE THREAD

**Issue by leifmadsen** [cloudwan/gohan#45]
When defining a schema, if you wish to add a parent relationship later, the order matters when the GUI is being created.

After creating a new schema `registration` where the parent object was `device`, the ability to add a new `registration` entry to the `device was not possible.

When the parent object was added, it was added as the last object in the object list for that schema. Once I used the schema builder to drag the `device_id` value to the top of the list, then I had the ability to add entries to the `registration` schema.

It appears the `propertiesOrder` is what changed to cause the GUI to provide the input mechanisms.

*Working*
```json
properties:
  auth_pass:
    description: Authorization Password
    permission:
      - create
      - update
    title: Auth Pass
    type: string
  auth_user:
    description: Authorization User
    permission:
      - create
      - update
    title: Auth User
    type: string
  callerid_name:
    description: CallerID Name
    permission:
      - create
      - update
    title: CID Name
    type: string
  callerid_num:
    description: CallerID Number
    permission:
      - create
      - update
    title: CID Number
    type: string
  device_id:
    description: parent object
    permission:
      - create
      - update
    relation: device
    title: device
    type: string
    unique: false
  id:
    description: ID
    permission:
      - create
    title: ID
    type: string
    view:
      - detail
  label:
    description: Line Label Display
    permission:
      - create
      - update
    title: Label
    type: string
  name:
    description: Name
    permission:
      - create
      - update
    title: Name
    type: string
  tenant_id:
    description: Tenant ID
    permission:
      - create
    title: Tenant ID
    type: string
    view:
      - detail
propertiesOrder:
  - device_id
  - tenant_id
  - id
  - name
  - auth_user
  - auth_pass
  - label
  - callerid_name
  - callerid_num
required:
  - device_id
type: object
```

**Comment by nati** [comment]
I think this is related with #44 but we need order schema based on dependency relationship

**Comment by leifmadsen** [comment]
@nati ah interesting. I'm not sure I totally follow. I think the ordering is definitely needed overall. It seems like there might be a code enhancement that would allow stepping through looking for relationships at a higher level, and then sort them for display or something.

Unfortunately I'm not that familiar with the code to know if what I'm saying is even a valid thought :)

**Comment by nati** [comment]
yes. 
I think we should reorder schemas when Gohan loads it based on the dependency.
also, we should detect circular dependencies.

**Comment by leifmadsen** [comment]
:+1:
