### ISSUE TITLE
Show only child properties once selecting a parent object

### ISSUE THREAD

**Issue by leifmadsen** [cloudwan/gohan#46]
Ran into an issue where we're trying to show two drop downs on a page, one of them being a list of parent objects, and the other being the list of child objects to the parent.

The issue is that the second drop down doesn't have a way (that I've found) that allows you to show only child objects for the parent object in the other drop down. Here is an example:

So I have the following schemas:
* Manufacturers
  * Models
  * Firmware (to be added)

Manufacturers is the parent to models (and firmware). When adding a Device to a Customer, the idea was that you would select the Manufacturer, the Model, and then the Firmware. The two dropdowns for Model and Firmware would be populated based on the Manufacturer that is selected.

Currently, all values in the child drop downs show.

## Manufacturer
```json
properties:
  description:
    description: Description
    permission:
      - create
      - update
    title: Description
    type: string
  id:
    description: ID
    permission:
      - create
    title: ID
    type: string
    view:
      - detail
  name:
    description: Name
    permission:
      - create
      - update
    title: Name
    type: string
    unique: true
  tenant_id:
    description: Tenant ID
    permission:
      - create
    title: Tenant ID
    type: string
    view:
      - detail
propertiesOrder:
  - id
  - name
  - description
  - tenant_id
required: null
type: object
```

### Model
```json
properties:
  id:
    description: ID
    permission:
      - create
    title: ID
    type: string
    view:
      - detail
  manufacturer_id:
    description: parent object
    permission:
      - create
    relation: manufacturer
    title: manufacturer
    type: string
    unique: false
  name:
    description: Name
    permission:
      - create
      - update
    title: Name
    type: string
  tenant_id:
    description: Tenant ID
    permission:
      - create
    title: Tenant ID
    type: string
    view:
      - detail
propertiesOrder:
  - id
  - name
  - tenant_id
  - manufacturer_id
required:
  - manufacturer_id
type: object
```

## Test Object with Manufacturer and Model
```json
properties:
  id:
    description: ID
    permission:
      - create
    title: ID
    type: string
    view:
      - detail
  manufacturer:
    description: Manufacturer
    permission:
      - create
      - update
    relation: manufacturer
    relation_property: manufacturer
    title: Manufacturer
    type: string
  model:
    description: Model
    permission:
      - create
      - update
    relation: model
    relation_property: model
    title: Model
    type: string
  tenant_id:
    description: Tenant ID
    permission:
      - create
    title: Tenant ID
    type: string
    view:
      - detail
propertiesOrder:
  - id
  - manufacturer
  - model
  - tenant_id
required: null
type: object
```

**Comment by Marquis42** [comment]
I'm working with Leif on this, and it seemed as though you might be able to make this function with a JavaScript extension.  I tried playing with the built-in gohan_model_list, but was unable to come up with something that worked properly.  Is this the right direction, and if so do you have a sample that can give us the clues we need to move forward?

**Comment by nati** [comment]
@leifmadsen  @Marquis42 

I believe this is about webui stuff, right?
We need to write custom javascript client code for now.
We can expend a custom backbone class for each schema.  
(I've used this for implementing schema editor 
https://github.com/cloudwan/chazuke/blob/master/js/setup.js#L1 )

I think we don't need "manufacturer" property in the test model, because "model" object 
has already parent's information.

 - add custom view
 - customize form code
 - get all "manufacturer" resources 
 - get all "model" resources 
 - construct manufacturer & model from

In future, we may support this as a common function in webui.

**Comment by nati** [comment]
OK please open this issue again. it you have additional questions
