### ISSUE TITLE
./run_test.sh: line 12: etcd: command not found

### ISSUE THREAD

**Issue by dragon28** [cloudwan/gohan#567]
I have found these issue related to etcd fail to lock path after I have installed gohan using "go get -u github.com/cloudwan/gohan" and execute the "./run_test.sh" inside the $GOPATH/src/github.com/cloudwan/gohan directory.

```
~/go/1.9/src/github.com/cloudwan/gohan$ ./run_test.sh 
./run_test.sh: line 12: etcd: command not found
```

go version go1.9 linux/amd64

Please look into this matter

Thanks

**Comment by morrisson** [comment]
Thank you for reporting this.

This happens due to the same reason written in #566 . Gohan unit tests are done with etcd, so you need to install etcd before running unit tests.

In addition, when you run unit tests, please use `make test` command.

Thanks,
Daisuke
