### ISSUE TITLE
API Server http://localhost:9091/ 404 page not found

### ISSUE THREAD

**Issue by dragon28** [cloudwan/gohan#568]
Hello People,

I am getting 404 page not found when I enter the API server at http://localhost:9091/

~/go/1.9/src/github.com/cloudwan/gohan$ gohan server --config-file ./etc/gohan.yaml
13:04:59.169 gohan.server INFO  logging initialized
13:04:59.169 gohan.db.migration INFO  migration: init
13:04:59.170 gohan.db.migration INFO  migration path: "db/migrations", version: 0
    Applied At                  Migration
    =======================================
13:04:59.170 gohan.schema INFO  Loading schema embed://etc/schema/gohan.json ...
13:04:59.172 gohan.schema INFO  Loading schema embed://etc/extensions/gohan_extension.yaml ...
13:04:59.173 gohan.schema INFO  Loading schema ./example_schema.yaml ...
13:04:59.182 gohan.db DEBUG  Registering schema namespace
13:04:59.182 gohan.db DEBUG  Registering schema event
13:04:59.183 gohan.db DEBUG  Registering schema extension
13:04:59.183 gohan.db DEBUG  Registering schema policy
13:04:59.183 gohan.db DEBUG  Registering schema schema
13:04:59.183 gohan.db DEBUG  Registering schema pet
13:04:59.183 gohan.db DEBUG  Registering schema order
13:04:59.183 gohan.metrics DEBUG  No graphite endpoints set in config file
13:04:59.183 gohan.server DEBUG  [Initializing Routes]
13:04:59.183 gohan.server DEBUG  [Plural Path] /gohan/v0.1/extensions
13:04:59.183 gohan.server DEBUG  [Singular Path] /gohan/v0.1/extensions/:id
13:04:59.183 gohan.server DEBUG  [Plural Path With Parents] /gohan/v0.1/extensions
13:04:59.184 gohan.server DEBUG  [Singular Path With Parents] /gohan/v0.1/extensions/:id
13:04:59.184 gohan.server DEBUG  [Plural Path] /gohan/v0.1/namespaces
13:04:59.184 gohan.server DEBUG  [Singular Path] /gohan/v0.1/namespaces/:id
13:04:59.184 gohan.server DEBUG  [Plural Path With Parents] /gohan/v0.1/namespaces
13:04:59.184 gohan.server DEBUG  [Singular Path With Parents] /gohan/v0.1/namespaces/:id
13:04:59.184 gohan.server DEBUG  [Plural Path] /gohan/v0.1/events
13:04:59.184 gohan.server DEBUG  [Singular Path] /gohan/v0.1/events/:id
13:04:59.184 gohan.server DEBUG  [Plural Path With Parents] /gohan/v0.1/events
13:04:59.184 gohan.server DEBUG  [Singular Path With Parents] /gohan/v0.1/events/:id
13:04:59.185 gohan.server DEBUG  [Plural Path] /gohan/v0.1/policies
13:04:59.185 gohan.server DEBUG  [Singular Path] /gohan/v0.1/policies/:id
13:04:59.185 gohan.server DEBUG  [Plural Path With Parents] /gohan/v0.1/policies
13:04:59.185 gohan.server DEBUG  [Singular Path With Parents] /gohan/v0.1/policies/:id
13:04:59.185 gohan.server DEBUG  [Plural Path] /gohan/v0.1/schemas
13:04:59.185 gohan.server DEBUG  [Singular Path] /gohan/v0.1/schemas/:id
13:04:59.185 gohan.server DEBUG  [Plural Path With Parents] /gohan/v0.1/schemas
13:04:59.185 gohan.server DEBUG  [Singular Path With Parents] /gohan/v0.1/schemas/:id
13:04:59.185 gohan.server DEBUG  [Plural Path] /v1.0/store/pets
13:04:59.185 gohan.server DEBUG  [Singular Path] /v1.0/store/pets/:id
13:04:59.185 gohan.server DEBUG  [Plural Path With Parents] /v1.0/store/pets
13:04:59.185 gohan.server DEBUG  [Singular Path With Parents] /v1.0/store/pets/:id
13:04:59.187 gohan.server DEBUG  [Plural Path] /v1.0/store/orders
13:04:59.187 gohan.server DEBUG  [Singular Path] /v1.0/store/orders/:id
13:04:59.187 gohan.server DEBUG  [Plural Path With Parents] /v1.0/store/orders
13:04:59.187 gohan.server DEBUG  [Singular Path With Parents] /v1.0/store/orders/:id
13:04:59.187 gohan.db.sql DEBUG  [0xc42040af60] Created transaction &sqlx.Tx{Tx:(*sql.Tx)(0xc42048a600), driverName:"sqlite3", unsafe:false, Mapper:(*reflectx.Mapper)(0xc4203414a0)}, isolation level: REPEATABLE READ
13:04:59.187 gohan.db.sql DEBUG  [0xc42040af60] Executing SQL query 'SELECT policys.`id` as `policys__id`, policys.`principal` as `policys__principal`, policys.`resource` as `policys__resource`, policys.`action` as `policys__action`, policys.`effect` as `policys__effect`, policys.`condition` as `policys__condition` FROM `policys`'
13:04:59.188 gohan.db.sql DEBUG  [0xc42040af60] Executing SQL query 'SELECT extensions.`id` as `extensions__id`, extensions.`code_type` as `extensions__code_type`, extensions.`url` as `extensions__url`, extensions.`path` as `extensions__path`, extensions.`code` as `extensions__code` FROM `extensions`'
13:04:59.188 gohan.db.sql DEBUG  [0xc42040af60] Executing SQL query 'SELECT namespaces.`id` as `namespaces__id`, namespaces.`name` as `namespaces__name`, namespaces.`description` as `namespaces__description`, namespaces.`prefix` as `namespaces__prefix`, namespaces.`parent` as `namespaces__parent`, namespaces.`version` as `namespaces__version`, namespaces.`metadata` as `namespaces__metadata` FROM `namespaces`'
13:04:59.188 gohan.db.sql DEBUG  [0xc42040af60] Committing transaction &sql.Transaction{transaction:(*sqlx.Tx)(0xc42040af60), db:(*sql.DB)(0xc420342f00), closed:false, isolationLevel:"REPEATABLE READ"}
13:04:59.189 gohan.server INFO  Gohan no jikan desuyo (It's time for dinner!)
13:04:59.189 gohan.server INFO  Build version: <unknown>
13:04:59.189 gohan.server INFO  Build timestamp: <unknown>
13:04:59.189 gohan.server INFO  Build host: <unknown>
13:04:59.189 gohan.server INFO  Starting Gohan Server...
13:04:59.189 gohan.server INFO      API Server http://localhost:9091/
13:04:59.189 gohan.server INFO      Web UI http://localhost:9091/webui/
13:05:05.789 gohan.server.middleware INFO  Started GET / for client 127.0.0.1:38722 data: 
13:05:05.789 gohan.server.middleware DEBUG  Request headers: map[User-Agent:[Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0] Cookie:[_ga=GA1.1.2106355880.1505313692] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Language:[en-US,en;q=0.5] Accept-Encoding:[gzip, deflate] Connection:[keep-alive] Upgrade-Insecure-Requests:[1]]
13:05:05.789 gohan.server.middleware DEBUG  Request body: 
13:05:05.794 gohan.server.middleware DEBUG  Response headers: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
13:05:05.795 gohan.server.middleware DEBUG  Response body: 404 page not found
13:05:05.796 gohan.server.middleware INFO  Completed 404 Not Found in 6.603426ms

**Comment by morrisson** [comment]
Hi.
As you can see attached log, URL for Web UI is http://localhost:9091/webui/ . You can login "demo" user or "admin" user without password if you do not change anything from gohan.yaml.
