### ISSUE TITLE
Broken schema handling

### ISSUE THREAD

**Issue by pax0r** [cloudwan/gohan#64]
When I've made a schema where in one of the fields `type` is missing Gohan exit with error:
`
panic: runtime error: invalid memory address or nil pointer dereference
`
which is not very helpful.

I think Gohan should print some more meaningful error like "property type is missing from field x on schema y". In current situation on complicated schema is may take quite a while to find where the bug was.

**Comment by nati** [comment]
Hi pax0r

I supposed this should be checked by Json schema validation.
Could you share your schema ?

**Comment by pax0r** [comment]
I fixed it already (I'll try to reproduce this later). Basically it was a schema with one resource which missed "type" on one of the fields.

**Comment by nati** [comment]
fixed
