### ISSUE TITLE
Can gohan_http post multipart/form-data?

### ISSUE THREAD

**Issue by yokoi-h** [cloudwan/gohan#87]
This is a question about gohan_http which is javascript built-in function.

Is it possible to upload file with gohan_http?
It seems to be able to send only json document.
https://github.com/cloudwan/gohan/blob/master/extension/otto/gohan_util.go#L186

If there are other ways to post file, could you tell me it?

Thank you

**Comment by nati** [comment]
Hi Yokoi-san

Currently, it isn't supported. 
We need to implement it in go code like this
https://github.com/cloudwan/gohan/blob/master/exampleapp/exampleapp.go#L26

**Comment by yokoi-h** [comment]
Hi nati-san,

Thank you for commenting.
So I need to implement module inside go and then call it from javascript extension?

**Comment by nati** [comment]
yes

**Comment by yokoi-h** [comment]
Thank you.

I also noticed it's very useful if gohan can post plain text data.
Can I propose a patch like [this](https://github.com/cloudwan/gohan/compare/master...yokoi-h:handle-contenttype?expand=1) that checks content-type and execute json.Marshal if it's "application/json"?

**Comment by yokoi-h** [comment]
Hi,

I created a patch to post text/plain data from gohan_http.
Can I send PR for this?
https://github.com/cloudwan/gohan/compare/master...yokoi-h:post-text-plain
